/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpbo;

import java.sql.Connection;
import java.sql.ResultSet;
import project.pelanggan;

/**
 *
 * @author Ella
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        KosongFormLogin();
    }
    
    
    public void KosongFormLogin() {
        txtusername.setEditable(true);
        txtpassword.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel = new javax.swing.JLabel();
        lblwarning = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1748, 1240));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 130, 60));

        lblwarning.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblwarning.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblwarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 300, 30));

        lbl_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_loginMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 140, 60));

        txtpassword.setBackground(new java.awt.Color(54, 91, 109));
        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(247, 247, 247));
        txtpassword.setBorder(null);
        txtpassword.setOpaque(false);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 322, 280, 30));

        txtusername.setBackground(new java.awt.Color(54, 91, 109));
        txtusername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtusername.setForeground(new java.awt.Color(247, 247, 247));
        txtusername.setBorder(null);
        txtusername.setOpaque(false);
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 280, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_loginMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select * from karyawan where username='"+txtusername.getText()+"' AND password='"+txtpassword.getText()+"'";
            java.sql.Connection conn=(Connection)project.Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
        
            if(rs.next()){
                this.setVisible(true);
                new menu().setVisible(true);
                dispose();
                this.pack();
                this.setLocationRelativeTo(null);
                this.setDefaultCloseOperation(project.login.EXIT_ON_CLOSE);
                lblwarning.setText("");
            }else{
                lblwarning.setText("username dan password Anda salah !");
            }
        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_lbl_loginMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        txtusername.setText("");
        txtpassword.setText("");
        lblwarning.setText("");
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lblwarning;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
