/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpbo;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ella
 */
public class pesanan extends javax.swing.JFrame {

    /**
     * Creates new form pesanan
     */
    public pesanan() {
        initComponents();
        KosongForm();
        tampil_data();
    }
    
    public void KosongForm(){
        txtkode_pesan.setEditable(true);
        txtkode_pel.setText(null);
        cmbbarang.setSelectedItem(this);
        txtnama_pesan.setText(null);
        txtbahan.setText(null);
        spin_jml.addChangeListener(null);
        txtharga.setText(null);
        txtsubtotal.setText(null);
    }
    
    public void tampil_data() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Kode Pesanan");
        tabel.addColumn("Kode Pelanggan");
        tabel.addColumn("Kode Item");
        tabel.addColumn("Nama Pesanan");
        tabel.addColumn("Bahan");
        tabel.addColumn("Jumlah");
        tabel.addColumn("Harga");
        tabel.addColumn("Subtotal");
        try {
            java.sql.Connection conn = (java.sql.Connection) 
                    projectpbo.Konfig.configDB();
            String sql = "select * from order";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8)});
            }
            tabelpesan.setModel(tabel);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsubtotal = new javax.swing.JTextField();
        kembali = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpesan = new javax.swing.JTable();
        exit = new javax.swing.JLabel();
        btnbatal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        spin_jml = new javax.swing.JSpinner();
        cmbbarang = new javax.swing.JComboBox<>();
        txtnama_pesan = new javax.swing.JTextField();
        txtbahan = new javax.swing.JTextField();
        txtkode_pel = new javax.swing.JTextField();
        txtkode_pesan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtbahan1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsubtotal.setBackground(new java.awt.Color(217, 217, 217));
        txtsubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsubtotal.setBorder(null);
        txtsubtotal.setOpaque(false);
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 373, 180, 20));

        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 50));

        tabelpesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpesanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpesan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 60, 470, 320));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 30, 30));

        btnbatal.setBackground(new java.awt.Color(128, 165, 175));
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 40));

        btnhapus.setBackground(new java.awt.Color(128, 165, 175));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 70, 40));

        btnedit.setBackground(new java.awt.Color(128, 165, 175));
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 70, 40));

        btnsimpan.setBackground(new java.awt.Color(128, 165, 175));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, 40));

        btntambah.setBackground(new java.awt.Color(128, 165, 175));
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 40));

        btncari.setBackground(new java.awt.Color(128, 165, 175));
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 70, 40));

        cari.setBackground(new java.awt.Color(217, 217, 217));
        cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cari.setBorder(null);
        cari.setOpaque(false);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 200, 20));

        txtharga.setBackground(new java.awt.Color(217, 217, 217));
        txtharga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtharga.setBorder(null);
        txtharga.setOpaque(false);
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 180, 20));
        jPanel1.add(spin_jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 60, -1));

        cmbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "b001", "b002", "b003", "b004" }));
        jPanel1.add(cmbbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        txtnama_pesan.setBackground(new java.awt.Color(217, 217, 217));
        txtnama_pesan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnama_pesan.setBorder(null);
        txtnama_pesan.setOpaque(false);
        txtnama_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_pesanActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 20));

        txtbahan.setBackground(new java.awt.Color(217, 217, 217));
        txtbahan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbahan.setBorder(null);
        txtbahan.setOpaque(false);
        txtbahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbahanActionPerformed(evt);
            }
        });
        jPanel1.add(txtbahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 190, 20));

        txtkode_pel.setBackground(new java.awt.Color(217, 217, 217));
        txtkode_pel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtkode_pel.setBorder(null);
        txtkode_pel.setOpaque(false);
        txtkode_pel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode_pelActionPerformed(evt);
            }
        });
        jPanel1.add(txtkode_pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 190, 20));

        txtkode_pesan.setBackground(new java.awt.Color(217, 217, 217));
        txtkode_pesan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkode_pesan.setBorder(null);
        txtkode_pesan.setOpaque(false);
        txtkode_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode_pesanActionPerformed(evt);
            }
        });
        jPanel1.add(txtkode_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgPesan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        txtbahan1.setBackground(new java.awt.Color(217, 217, 217));
        txtbahan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbahan1.setBorder(null);
        txtbahan1.setOpaque(false);
        txtbahan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbahan1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtbahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 190, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkode_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode_pesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkode_pesanActionPerformed

    private void txtkode_pelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode_pelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkode_pelActionPerformed

    private void txtbahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbahanActionPerformed

    private void txtnama_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_pesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_pesanActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        KosongForm();
    }//GEN-LAST:event_btntambahActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Yakin Keluar aplikasi???",
            "Yakin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void tabelpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpesanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelpesanMouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select * from pelanggan ";
            java.sql.Connection conn=(Connection)projectpbo.Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
        
            if(rs.next()){
                new menu().setVisible(true);
                dispose();
                this.pack();
                this.setLocationRelativeTo(null);
                this.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
            }else{

            }
        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_kembaliMouseClicked

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into order values('"
            + txtkode_pesan.getText() + "','"
            + txtkode_pel.getText() + "','"
            + cmbbarang.getSelectedItem() + "','"
            + txtnama_pesan.getText() + "','"
            + txtbahan.getText() + "','"
            + spin_jml.getChangeListeners() + "','"
            + txtharga.getText() + "','"
            + txtsubtotal.getText() + "')";
            java.sql.Connection conn = (java.sql.Connection)
            projectpbo.Konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) projectpbo.Konfig.configDB();
            String sql = "update  order set kode_pelanggan='" + txtkode_pel.getText()
            + txtkode_pesan.getText() + "','"
            + cmbbarang.getSelectedItem() + "','"
            + txtnama_pesan.getText() + "','"
            + txtbahan.getText() + "','"
            + spin_jml.getAccessibleContext() + "','"
            + txtharga.getText() + "','"
            + txtsubtotal.getText() + "','"
            + "' where kode_order='" + txtkode_pesan.getText() + "'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di Koreksi");
            tampil_data();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses Edit data Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) projectpbo.Konfig.configDB();
            String sql = "delete from order where kode_order='" + txtkode_pesan.getText() + "' ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            tampil_data();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        KosongForm();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) project.Konfig.configDB();

            String sql = "Select * from order where kode_order='" + cari.getText() + "' or kode_pelanggan='" + cari.getText() + "'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                txtkode_pesan.setText(rs.getString(1));
                txtkode_pel.setText(rs.getString(2));
                cmbbarang.setSelectedItem(rs.getString(3));
                txtnama_pesan.setText(rs.getString(4));
                txtbahan.setText(rs.getString(5));
                spin_jml.setValue(rs.getString(6));
                txtharga.setText(rs.getString(7));
                txtsubtotal.setText(rs.getString(8));
                JOptionPane.showMessageDialog(null, "Data order : "
                    + cari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void txtbahan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbahan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbahan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> cmbbarang;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kembali;
    private javax.swing.JSpinner spin_jml;
    private javax.swing.JTable tabelpesan;
    private javax.swing.JTextField txtbahan;
    private javax.swing.JTextField txtbahan1;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode_pel;
    private javax.swing.JTextField txtkode_pesan;
    private javax.swing.JTextField txtnama_pesan;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
